packages:
  - "backend-sanity"

allowBuilds:
  "@parcel/watcher": false
  core-js: false
  core-js-pure: false
  es5-ext: false
  esbuild: false
  netlify-cli: false
  sharp: false
  uglifyjs-webpack-plugin: false
  unix-dgram: false
  
