packages:
  - "backend-sanity"

allowBuilds:
  "@parcel/watcher": false
  core-js: false
  core-js-pure: false
  es5-ext: false
  uglifyjs-webpack-plugin: false

overrides:
  "@types/react": "^18.3.31"
  "@types/react-dom": "^18.3.7"
